# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-07 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '分类', 'verbose_name_plural': '分类'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': '类别', 'verbose_name_plural': '类别'},
        ),
        migrations.AlterModelTable(
            name='category',
            table='blog_category',
        ),
        migrations.AlterModelTable(
            name='tag',
            table='blog_tag',
        ),
    ]
